#!/bin/bash
set -e

case "$1" in
    remove|purge)
        if command -v systemctl >/dev/null 2>&1; then
            if [[ "$(/usr/bin/systemctl is-active supervisor.service 2>/dev/null || true)" == "active" ]]; then
                echo "Stopping supervisor.service"
                /usr/bin/systemctl stop supervisor.service || true
            fi
            /usr/bin/systemctl disable supervisor.service || true
            if [[ "$(/usr/bin/systemctl is-active btgatt-config.service 2>/dev/null || true)" == "active" ]]; then
                echo "Stopping btgatt-config.service"
                /usr/bin/systemctl stop btgatt-config.service || true
            fi
            /usr/bin/systemctl disable btgatt-config.service || true
        fi
        echo "Remove success."
        ;;
    upgrade)
        if command -v systemctl >/dev/null 2>&1; then
            if [[ "$(/usr/bin/systemctl is-active supervisor.service 2>/dev/null || true)" == "active" ]]; then
                echo "Stopping supervisor.service for upgrade"
                /usr/bin/systemctl stop supervisor.service || true
            fi
            if [[ "$(/usr/bin/systemctl is-active btgatt-config.service 2>/dev/null || true)" == "active" ]]; then
                echo "Stopping btgatt-config.service for upgrade"
                /usr/bin/systemctl stop btgatt-config.service || true
            fi
        fi
        ;;
esac

exit 0
