#!/bin/bash

set -e

if [[ "$(systemctl is-active home-assistant.service)" == "active" ]]; then
    echo "Stopping home-assistant.service"
    systemctl stop home-assistant.service
fi

if [[ "$(systemctl is-active matter-server.service)" == "active" ]]; then
    echo "Stopping matter-server.service"
    systemctl stop matter-server.service
fi

