#!/bin/bash
set -e

# 停止服务
if [ "$1" = "remove" ]; then

    # If the home-assistant service is running or exists, stop it 
    if [[ "$(systemctl is-active home-assistant.service)" == "active" ]]; then
        echo "Stopping home-assistant.service"
        systemctl stop home-assistant.service
    fi

    # If the matter-server service is running or exists, stop it 
    if [[ "$(systemctl is-active matter-server.service)" == "active" ]]; then
        echo "Stopping matter-server.service"
        systemctl stop matter-server.service
    fi

    rm -rf /usr/local/bin/python3 /usr/local/bin/python
    rm -rf /usr/local/bin/pip3 /usr/local/bin/pip
    rm -rf /usr/local/bin/python3-config
fi

exit 0
