ExternalProject_Add(
  node
  URL https://nodejs.org/download/release/v20.19.4/node-v20.19.4-linux-arm64.tar.xz
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ""
  INSTALL_COMMAND "")

ExternalProject_Get_Property(node SOURCE_DIR)

install(
  DIRECTORY ${SOURCE_DIR}/bin/
  TYPE BIN
  FILE_PERMISSIONS OWNER_READ OWNER_WRITE WORLD_READ WORLD_EXECUTE
  COMPONENT node)
install(
  DIRECTORY ${SOURCE_DIR}/lib/
  TYPE LIB
  FILE_PERMISSIONS OWNER_READ OWNER_WRITE WORLD_READ WORLD_EXECUTE
  COMPONENT node)
install(
  DIRECTORY ${SOURCE_DIR}/include/
  TYPE INCLUDE
  FILE_PERMISSIONS OWNER_READ OWNER_WRITE WORLD_READ
  COMPONENT node)

set(CPACK_DEBIAN_NODE_PACKAGE_SECTION javascript)
