#!/bin/bash
set -e

# Note: For offline installation, place packages in /usr/lib/thirdreality/archives_zigbee2mqtt directory

# Constants
DEFAULT_APT_CACHE="/var/cache/apt/archives"
THIRDREALITY_ARCHIVES="/usr/lib/thirdreality/archives_zigbee2mqtt"
THIRDREALITY_CONF="/lib/thirdreality/conf"
MOSQUITTO_DIR="/etc/mosquitto"
ZIGBEE2MQTT_DIR="/opt/zigbee2mqtt/data"
LOG_FILE="/var/log/thirdreality-zigbee-mqtt-install.log"


fix_manual_install() {
    echo "Installing zigbee2mqtt files..."
    
    if [[ "$(/usr/bin/systemctl is-active mosquitto.service)" == "active" ]]; then
        systemctl stop mosquitto.service >/dev/null || true
    fi

    if [[ "$(/usr/bin/systemctl is-active zigbee2mqtt.service)" == "active" ]]; then
        systemctl stop zigbee2mqtt.service >/dev/null || true
    fi

    if [ -f "/usr/lib/thirdreality/post-fix-zigbee2mqtt.sh" ]; then
        chmod +x /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh
    fi

    if [ -f "/opt/zigbee2mqtt/scripts/zigbee2mqtt_blz_reset.sh" ]; then
        chmod +x /opt/zigbee2mqtt/scripts/zigbee2mqtt_blz_reset.sh
    fi

    if [ -f "/opt/zigbee2mqtt/scripts/z2m-permit-on-passlist.sh" ]; then
        chmod +x /opt/zigbee2mqtt/scripts/zigbee2mqtt_blz_reset.sh
    fi    
}

case "$1" in
    configure)
        if [ -z "$2" ]; then
            # Fresh installation
            fix_manual_install
            #if [ -d "/opt/zigbee2mqtt/data" ]; then
            #    rm -rf /opt/zigbee2mqtt/data/*
            #fi
            # 以前首次安装才清空数据， 从养老项目开始，不再删除这些文件
        else
            # Upgrade operation
            fix_manual_install
            # 升级时什么也不覆盖、不清空
        fi  

        echo "=========================================================="
        echo "If you manually install zigbee-mqtt.deb, please execute"
        echo "the following script after installation:"
        echo "/usr/lib/thirdreality/post-fix-zigbee2mqtt.sh"
        echo "========================================================"
        
    ;;

    fix-dependency)
        # Manual dependency fixing
        if [ -e "/usr/lib/thirdreality/post-fix-zigbee2mqtt.sh" ]; then
            echo "Excuting /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh ..."
            chmod +x /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh
            /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh > /dev/null || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

