#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /opt/zigbee2mqtt/data/*
        rm -rf /opt/zigbee2mqtt/
        rm -rf /opt/zigbee-herdsman/
    ;;
    remove|abort-install|abort-upgrade|disappear)
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

