#!/bin/bash
set -e

# 中文说明： 是否离线安装，如果离线安装，则需要将包放在/usr/lib/thirdreality/archives_zigbee2mqtt目录下

# Constants
DEFAULT_APT_CACHE="/var/cache/apt/archives"
THIRDREALITY_ARCHIVES="/usr/lib/thirdreality/archives_zigbee2mqtt"
THIRDREALITY_CONF="/lib/thirdreality/conf"
MOSQUITTO_DIR="/etc/mosquitto"
ZIGBEE2MQTT_DIR="/opt/zigbee2mqtt/data"
LOG_FILE="/var/log/thirdreality-zigbee-mqtt-install.log"


fix_manual_install() {
    echo "fix manual install ..."
    # 检查是安装还是升级
    echo "Install zigbee2mqtt files ..."
    
    if [[ "$(/usr/bin/systemctl is-active mosquitto.service)" == "active" ]]; then
        systemctl stop mosquitto.service >/dev/null || true
    fi

    if [[ "$(/usr/bin/systemctl is-active zigbee2mqtt.service)" == "active" ]]; then
        systemctl stop zigbee2mqtt.service >/dev/null || true
    fi

    if [ -f "/usr/lib/thirdreality/post-fix-zigbee2mqtt.sh" ]; then
        chmod +x /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh
    fi

    if [ -f "/opt/zigbee2mqtt/scripts/zigbee2mqtt_blz_reset.sh" ]; then
        chmod +x /opt/zigbee2mqtt/scripts/zigbee2mqtt_blz_reset.sh
    fi
}

case "$1" in
    configure)
        if [ -z "$2" ]; then
            # 全新安装
            fix_manual_install
            if [ -d "/opt/zigbee2mqtt/data" ]; then
                rm -rf /opt/zigbee2mqtt/data/*
            fi
        else
            # 升级操作
            fix_manual_install
        fi    
        
    ;;

    fix-dependency)
        # Main execution
        if [ -e "/usr/lib/thirdreality/post-fix-zigbee2mqtt.sh" ]; then
            chmod +x /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh
            /usr/lib/thirdreality/post-fix-zigbee2mqtt.sh > /dev/null || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

