#!/bin/bash
set -e

# 检查是安装还是升级
if [ "$1" = "configure" ]; then
    if [ -f "/usr/lib/thirdreality/images/upgrade_firmware.sh" ]; then
        chmod +x /usr/lib/thirdreality/images/upgrade_firmware.sh
    fi
    
    # systemctl daemon-reload || true
    # systemctl disable thirdreality-firmware-upgrade.service || true

    # echo "Launching firmware upgrade service in background..."
    # systemd-run --no-block --unit=firmware-upgrade \
    #     --description="Async firmware upgrade" \
    #     systemctl start thirdreality-firmware-upgrade.service || true

    # echo "Firmware upgrade service scheduled in background."

elif [ "$1" = "fix-dependency" ]; then
    echo "fix-dependency"
    if [ -f "/usr/lib/thirdreality/images/upgrade_firmware.sh" ]; then
        /usr/lib/thirdreality/images/upgrade_firmware.sh || true
    fi
fi

exit 0

