#!/bin/bash

[ -f "/usr/bin/python3.13" ] || \
[ -f "/usr/local/bin/python3.13" ] || \
[ -f "/usr/local/python3/bin/python3.13" ] || {
    echo "Error: Python 3.13 not found in any of:" >&2
    echo "  /usr/bin/python3.13" >&2
    echo "  /usr/local/bin/python3.13" >&2
    echo "  /usr/local/python3/bin/python3.13" >&2
    exit 1
}

if [[ "$(/usr/bin/systemctl is-active home-assistant.service)" == "active" ]]; then
    echo "Stopping home-assistant.service"
    /usr/bin/systemctl stop home-assistant.service
fi

if [[ "$(/usr/bin/systemctl is-active matter-server.service)" == "active" ]]; then
    echo "Stopping matter-server.service"
    /usr/bin/systemctl stop matter-server.service
fi

if [[ -e "/srv/homeassistant" ]]; then
    rm -rf /srv/homeassistant
fi
