#!/bin/bash
set -e
function info { echo -e "\e[32m[info] $*\e[39m"; }
function warn  { echo -e "\e[33m[warn] $*\e[39m"; }
function error { echo -e "\e[31m[error] $*\e[39m"; exit 1; }

# 检查是安装还是升级
if [ "$1" = "configure" ]; then
	rm -rf /usr/share/hassio/homeassistant/zha.conf
	rm -rf /usr/share/hassio/homeassistant/zha.conf.bak

	rm -rf /var/lib/homeassistant/zha.conf
	rm -rf /var/lib/homeassistant/zha.conf.bak

	mkdir -p /var/lib/homeassistant
	mkdir -p /var/lib/homeassistant/homeassistant
	mkdir -p /var/lib/homeassistant/matter_server

    mkdir -p /data /updates
    chmod 777 /data /updates
    touch /tmp/chip_kvs && chmod 766 /tmp/chip_kvs || { echo "[WARN]Failed to setup directories"; }	

	if [ -e "/srv/homeassistant/bin/home_assistant_boot_check.sh" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_boot_check.sh > /dev/null 2>&1
	fi

	if [ -e "/srv/homeassistant/bin/home_assistant_blz_reset.sh" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_blz_reset.sh > /dev/null 2>&1
	fi

	if [ -e "/srv/homeassistant/bin/home_assistant_zha_enable.py" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_zha_enable.py > /dev/null 2>&1
	fi

	if [ -e "/srv/homeassistant/bin/home_assistant_z2m_enable.py" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_z2m_enable.py > /dev/null 2>&1
	fi

	if [ -e "/srv/homeassistant/bin/home_assistant_zigbee_fix.sh" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_zigbee_fix.sh > /dev/null 2>&1
	fi

	info "Update zigbee default config ..."
	if [ -e "/srv/homeassistant/bin/home_assistant_init.sh" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_init.sh > /dev/null 2>&1

		if [ -e "/var/lib/homeassistant/homeassistant/configuration.yaml" ]; then
			/srv/homeassistant/bin/home_assistant_init.sh > /dev/null 2>&1 || {
        		echo "[WARN]home_assistant_init.sh failed, but continuing..." 
    		}
		fi
	fi

	# Fix matter server vendorId
	if [ -e "/srv/homeassistant/bin/home_assistant_matter_fix.sh" ]; then
		chmod +x /srv/homeassistant/bin/home_assistant_matter_fix.sh > /dev/null 2>&1

		if [ -e "/var/lib/homeassistant/matter_server/chip.json" ]; then
			/srv/homeassistant/bin/home_assistant_matter_fix.sh > /dev/null 2>&1 || {
        		echo "[WARN]home_assistant_matter_fix.sh failed, but continuing..." 
    		}
		fi
	fi

	/usr/bin/systemctl daemon-reload
	/usr/bin/systemctl enable home-assistant.service
	/usr/bin/systemctl enable matter-server.service

	msg=$(iw dev wlan0 link 2>&1)
    if echo "$msg" | grep -q "Connected"; then
        /usr/bin/systemctl start home-assistant.service
        /usr/bin/systemctl start matter-server.service
	fi
	
	info "Install HomeAssistant-Core success."
elif [ "$1" = "fix-dependency" ]; then
    echo "fix-dependency"
fi

exit 0

