#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
	rm -rf /var/lib/homeassistant/zha.conf
	rm -rf /var/lib/homeassistant/zha.conf.bak
	rm -rf /var/lib/homeassistant/zigpy-backup.json

	if [ -f "/usr/local/bin/zigpy_help.sh" ]; then
		chmod +x /usr/local/bin/zigpy_help.sh
	fi
	
	# Check if the architecture is aarch64
	if [ "$(uname -m)" = "aarch64" ]; then
		SCRIPT_PATH="/srv/homeassistant/bin/home_assistant_init.sh"

		# Check if the script exists
		if [ -f "$SCRIPT_PATH" ]; then
			# Execute the script
			chmod +x "$SCRIPT_PATH"
			if [ -e "/var/lib/homeassistant/homeassistant/configuration.yaml" ]; then
				"$SCRIPT_PATH" > /dev/null 2>&1 || {
					echo "[WARN] home_assistant_init.sh failed, but continuing..." 
				}
			fi
		else
			echo "Warn: Script $SCRIPT_PATH not found."
		fi
	fi
elif [ "$1" = "fix-dependency" ]; then
    echo "fix-dependency"
fi

exit 0

